# Generated by Django 3.1.3 on 2023-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sep', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=10)),
                ('zip', models.IntegerField()),
                ('add', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('total', models.IntegerField()),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
            ],
        ),
    ]
