# Generated by Django 3.1.3 on 2023-11-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='sep',
            new_name='place',
        ),
        migrations.AddField(
            model_name='hospital',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='type_short',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='tel',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
